<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
//    protected $table = 'users';

    const PRIVILEGE_CUSTOMER = 1; // 用户权限
    const PRIVILEGE_SERVICE = 2; // 客服权限
    const PRIVILEGE_ADMIN = 3; // 管理员权限


    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }

    protected $fillable = [
        'name', 'email', 'password', 'privilege',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function privilege($ind = null)
    {
        $arr = [
            self::PRIVILEGE_CUSTOMER => '用户',
            self::PRIVILEGE_SERVICE => '客服',
            self::PRIVILEGE_ADMIN => '管理员',
        ];
        if ($ind !== null) {
            return array_key_exists($ind, $arr) ? $arr[$ind] : $arr[self::PRIVILEGE_CUSTOMER];
        }
        return $arr;

    }


}
